version: '3.3'

services:
  backend:
    container_name: ylms-backend
    build:
      context: ./backend/.
      dockerfile: ../deployment/backend/Dockerfile
    ports:
      - 3005:3005
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ylms

  postgres:
    image: postgres:latest
    container_name: ylms-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ylms"
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - ./deployment/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - ylms

  frontend:
    container_name: ylms-frontend
    build:
      context: ./frontend/.
      dockerfile: ../deployment/frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - ylms

  nginx:
    image: nginx:latest
    container_name: ylms-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - ylms


networks:
  ylms:
    driver: bridge